@Restaurants.API_HostAddress = https://localhost:7075

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1002

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/by-name/KFC

###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###
POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
    "Name": "Spicy Delights2",
    "Description": "A culinary experience like no other",
    "Category": "Fine Dining",
    "HasDelivery": false,
    "ContactEmail": "info@gourmetdelights.com",
    "ContactNumber": "555-123-4567",
    "City": "Metropolis",
    "Street": "456 Gourmet Avenue",
    "PostalCode": "54321"
}

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  //CreateRestaurantDto
}

###
POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
    "Name": "American Cusine 2",
    "Description": "A culinary experience like no other",
    "Category": "Italian",
    "HasDelivery": false,
    "ContactEmail": "info@gourmetdelights.com",
    "ContactNumber": "555-123-4567",
    "City": "Metropolis",
    "Street": "456 Gourmet Avenue",
    "PostalCode": "10-010"
}
GET {{Restaurants.API_HostAddress}}/api/restaurants

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
    "Name": "American Cusine 2",
    "Description": "A culinary experience like no other",
    "Category": "Indian",
    "HasDelivery": false,
    "ContactEmail": "info@gourmetdelights.com",
    "ContactNumber": "555-123-4567",
    "City": "Metropolis",
    "Street": "456 Gourmet Avenue",
    "PostalCode": "10-010"
}

###

@id=0
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/3003

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/3002
Content-Type: application/json

{
  "Name": "Sample path",
  "Description": "this is a sample restaurant description.",
  "HashDelivery": true
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3002

###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/1002/dishes
Content-Type: application/json

{
   "name": "Espaguetti",
    "description": "Spaguetti con salsa bolognesa",
    "Price": 6,
    "KiloCalories": 750

}

###
